### ISSUE TITLE
请问sky对战平台得到授权了吗？我见他们1.27也在用flo。

### ISSUE THREAD

**Issue by dianso** [w3champions/flo#31]
请问sky对战平台得到授权了吗？我见他们1.27也在用flo。

安装目录有flo-worker.exe

日志文件也是：flo-logs

Sep 04 18:53:58.819  INFO flo_client::message::ws: version: 0.16.0
Sep 04 18:53:58.819  INFO flo_platform: sky vs === installation_path: "D:/W3127/Warcraft III"
Sep 04 18:53:58.819  INFO flo_platform::war3::windows: get_war3_version: path: "D:/W3127/Warcraft III\\Warcraft III.exe"
Sep 04 18:53:58.819  INFO flo_platform::war3::windows: get_war3_version result: [1, 0, 0, 1]
Sep 04 18:53:58.819  INFO flo_platform: sky vs === war3 version: 1.0.0.1
Sep 04 18:53:58.819 DEBUG flo_lan::udp::publisher:  -->sky:: new UdpPublisher
Sep 04 18:53:58.822 DEBUG flo_lan::udp::publisher: -->sky socket bind : 127.0.0.1:6114
Sep 04 18:53:58.822 DEBUG worker: flo_lan::udp::publisher:  -->sky:: start UdpPublisher worker
Sep 04 18:53:58.822 DEBUG flo_client::message::ws: listen on 55213
Sep 04 18:53:58.822 DEBUG worker{id=1}: flo_client::controller::stream: connect addr: 47.98.137.97:3550
Sep 04 18:53:58.875 DEBUG worker{id=1}: flo_client::controller::stream: connected
Sep 04 18:53:58.927 DEBUG worker{id=1}: flo_client::controller::stream: player = 49, status = Idle player_id=49
Sep 04 18:53:58.927  INFO flo_client::controller: player session replaced: game_id = None player_id=49
Sep 04 18:53:58.927 DEBUG flo_client::ping: add addr: 116.62.202.141:3552
Sep 04 18:53:59.142 DEBUG worker: tungstenite::handshake::server: Server handshake done.    
Sep 04 18:54:02.158 DEBUG flo_client::ping::collect: ping timeout address="116.62.202.141:3552"

**Comment by dianso** [comment]
听说软著也在申请，可别被申请成功了，flo彻底成人家的了。

**Comment by fluxxu** [comment]
我们确实是和他们有一些合作。
非常感谢你的提醒。
