### ISSUE TITLE
Linux is not building

### ISSUE THREAD

**Issue by frosk1** [w3champions/flo#32]
There is a parameter missing in the ClientPlatformInfo class for Linux builds, the user_battlenet_id. 

Line 159 in file flo/crates/platform/src/lib.rs

`    Ok(ClientPlatformInfo {
      user_data_path,
      installation_path,
      version,
      executable_path,
      ptr
    })
  }`

**Comment by fluxxu** [comment]
Sorry for the delayed response. Since you're using Linux, you can disregard the error. The client code has never been functional on Linux.
You can build the controller or node using `cargo build -p <package_name>`
Or you can set `user_battlenet_id` to `todo!()`
