### ISSUE TITLE
[macos] flo-worker not supported on intel arch

### ISSUE THREAD

**Issue by Mutantx** [w3champions/flo#45]
# Description

`flo-worker` not provided for intel arch in v0.17.0

# Context

flo release [v0.17.0](https://github.com/w3champions/flo/releases/tag/v0.17.0) - latest
- `/Applications/w3champions.app/Contents/Resources/app.asar.unpacked/flo-worker: Mach-O 64-bit executable arm64`
- `flo-worker` built for arm architecture supporting apple silicon/m series are working.

flo release [v0.16.1](https://github.com/w3champions/flo/releases/tag/v0.16.1)
- `flo-worker: Mach-O 64-bit executable x86_64`
- built for intel architecture

# Possible Implementations

⏩ **add flo-worker for intel arch**

- compile flo-worker for intel arch _(some options shown below)_
- https://github.com/w3champions/launcher/blob/82f6d0190de00976072120e99cfdabc43b812e74/src/background-thread/flo/flo-utils.service.ts#L27
- https://github.com/w3champions/launcher/blob/82f6d0190de00976072120e99cfdabc43b812e74/vue.config.js#L20-L29

 ⏩ **Revert back to x86_64 (arm based macs can support this with Rosetta 2).**
- change github-actions runner label from `macos-latest` to `macos-15-large` or `macos-14-large` - [ref](https://github.com/actions/runner-images#available-images)
https://github.com/w3champions/flo/blob/8323f8d59c9e09d819cf9ee84e3b4763447dbaf4/.github/workflows/release.yml#L13
  - currently, 
    - arm: `macos-latest` --> macOS 14 Arm64
    - intel: `macos-15-large` --> macOS 15 beta && `macos-14-large` --> macOS 14
- Split cargo build in build and pass --target for x86_64
https://github.com/w3champions/flo/blob/8323f8d59c9e09d819cf9ee84e3b4763447dbaf4/.github/workflows/release.yml#L45-L50
- cargo build --target 
  - assumption is that currently "The default is the host architecture" [ref](https://doc.rust-lang.org/cargo/commands/cargo-build.html#compilation-options) provided by ci/cd runner.
- cargo config update

**Comment by BogdanW3** [comment]
Reverted mac runner to mac-13 to go back to x86_64
