### ISSUE TITLE
Usage Instructions

### ISSUE THREAD

**Issue by erfanmola** [w3champions/flo#5]
Hi, Any Instructions about how to use this in order to run our own FLO Server ? And What versions of game does this Server Support ? Can we run it on 1.31 game versions ?

**Comment by Miezhiko** [comment]
@erfanmola there is instruction I've written for install on debian/ubuntu https://github.com/w3champions/flo/blob/develop/INSTALL.md

regarding possibility of older game versions support I'm not fully sure, @fluxxu may know better

**Comment by fluxxu** [comment]
1.31 is not supported because reforged changed the LAN protocol

**Comment by erfanmola** [comment]
> 1.31 is not supported because reforged changed the LAN protocol

Can you suggest anyway that I can run my own Server on 1.31 ? I tried pvpgn, but it is until 1.28.5

**Comment by fluxxu** [comment]
it's not possible unless we add code to implement 1.31 LAN protocol

**Comment by erfanmola** [comment]
> it's not possible unless we add code to implement 1.31 LAN protocol

Can I look forward to this ?
